name: "Continuous Integration"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup node
        uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7
        with:
          node-version-file: 'package.json'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Run linter
        run: yarn lint

      - name: Run tests
        run: yarn test
